
CREATE TABLE MEMBER(
	MEMBERNUM INT PRIMARY KEY,
	ID VARCHAR(100) UNIQUE NOT NULL,
	PW VARCHAR(100) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	NICKNAME VARCHAR(100) UNIQUE NOT NULL,
	BIRTH DATE,
	PH VARCHAR(100) UNIQUE,
	PROFILE VARCHAR(500) NOT NULL,
	GRADE VARCHAR(100)
)











-------------------------------QUERY TEST---------------------------------


SELECT * FROM MEMBER;
INSERT INTO MEMBER(MEMBERNUM,ID,PW,NAME,NICKNAME,BIRTH,PH,PROFILE,GRADE)
	VALUES((SELECT NVL(MAX(MEMBERNUM),0)+1 FROM MEMBER),'a@a.c','a','석진','진',(TO_DATE('19930910','YYYY-MM-DD')),'010-1234-5678','1.png','일반');
	
INSERT INTO MEMBER(MEMBERNUM,ID,PW,NAME,NICKNAME,BIRTH,PH,PROFILE,GRADE)
	VALUES((SELECT NVL(MAX(MEMBERNUM),0)+1 FROM MEMBER),'1','1234','아','나',(TO_DATE('19930910','YYYY-MM-DD')),'01022222222','jpg','일반');
		
INSERT INTO MEMBER(MEMBERNUM,ID,PW,NAME,NICKNAME,BIRTH,PH,GRADE)
	VALUES((SELECT NVL(MAX(MEMBERNUM),0)+1 FROM MEMBER),'CAPTAIN','1234','캡틴','캡틴큐','1995-08-16','01055555555','신입');
	
INSERT INTO MEMBER(MEMBERNUM,ID,PW,NAME,NICKNAME,BIRTH,PH,GRADE)
	VALUES((SELECT NVL(MAX(MEMBERNUM),0)+1 FROM MEMBER),'THANOS','1234','타노스','반반맨','1995-08-17','01066666666','관리자');
	
	SELECT M.MEMBERNUM,ID,PW,NAME,NICKNAME, TO_CHAR(BIRTH,'YYYY-MM-DD'),PH,PROFILE,GRADE, BOARDNUM, TITLE FROM MEMBER M INNER JOIN BOARD B ON M.MEMBERNUM = B.MEMBERNUM WHERE ID='a@a.c';
	SELECT * FROM BOARD;
DROP TABLE MEMBER;
DELETE FROM MEMBER;
DELETE FROM BOARD;
INSERT INTO BOARD(BOARDNUM, MEMBERNUM, CATEGORY, TITLE, CONTENTS) VALUES((SELECT NVL(MAX(BOARDNUM),0) FROM BOARD)+1, 1, '자유게시판','카메라안삼~','사실 삼 ...');
 
SELECT * FROM ALL_TABLES;
SELECT ID FROM MEMBER WHERE ID='a@a.c' AND PW='b';

CREATE TABLE BOARD(
	BOARDNUM INT PRIMARY KEY,
	MEMBERNUM INT,
	CATEGORY VARCHAR(100) NOT NULL,
	TITLE VARCHAR(100) NOT NULL,
	CONTENTS VARCHAR(500) NOT NULL,
	BOARDDATE DATE DEFAULT SYSDATE,
	PRICE INT,
	IMAGE VARCHAR(300),
	PRODUCTCATEGORY VARCHAR(100),
	COMPANY VARCHAR(100),
	STATE VARCHAR(100),
	VIEWCOUNT INT,
	COMMENDNUM INT
);


INSERT INTO BOARD(BOARDNUM,MEMBERNUM,CATEGORY,TITLE,CONTENTS)
	VALUES((SELECT NVL(MAX(MEMBERNUM),0)+1 FROM MEMBER),'1','a','제목','내용');