CREATE TABLE MEMBER(
	MEMBERNUM INT PRIMARY KEY,
	ID VARCHAR(100) UNIQUE NOT NULL,
	PW VARCHAR(100) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	NICKNAME VARCHAR(100) UNIQUE NOT NULL,
	BIRTHDAY DATE,
	PH INT UNIQUE ,
	PROFILE VARCHAR(100),
	GRADE VARCHAR(100)
);

DROP TABLE MEMBER;
DROP TABLE REVIEW;
DROP TABLE BOARD;

SELECT * FROM MEMBER;
DELETE TABLE MEMBER:

INSERT INTO MEMBER (MEMBERNUM, ID, PW, NAME, NICKNAME, PH, GRADE) 
			VALUES((SELECT NVL(MAX(MEMBERNUM),0) + 1 FROM MEMBER), 'ironman', '1234', '아이언맨', '아이언맨짱', 01012341234, '일반');

			
INSERT INTO MEMBER (MEMBERNUM, ID, PW, NAME, NICKNAME, PH, GRADE) 
			VALUES((SELECT NVL(MAX(MEMBERNUM),0) + 1 FROM MEMBER), 'captain', '12345', '캡틴', '캡틴큐', 01024949299, '신입');

INSERT INTO MEMBER (MEMBERNUM, ID, PW, NAME, NICKNAME, PH, GRADE) 
			VALUES((SELECT NVL(MAX(MEMBERNUM),0) + 1 FROM MEMBER), 'thanos', '6666', '타노스', '반반맨', 01095847586, '관리자');
			
			
UPDATE MEMBER SET GRADE='신입' WHERE MEMBERNUM='1';