CREATE TABLE REPORT(
	REPORTNUM INT PRIMARY KEY,		 -- 신고넘버 PK
	MEMBERNUM INT,					 -- 멤버넘버 
	REPORTER VARCHAR(100),			 -- 신고자
	REPORTCONTENTS VARCHAR(500), 	 -- 신고 내용
	REPORTDATE DATE DEFAULT SYSDATE, -- 신고 날짜
	ACCOUNTSTOP DATE DEFAULT SYSDATE -- 활동 정지 기간
);


